networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data: {}
  #grafana-data: {}
  alertmanager-data: {}

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ~/promgrafnode/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ~/promgrafnode/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ~/promgrafnode/prometheus:/prometheus

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring
    

  grafana:
    image: grafana/grafana-oss:main-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ~/promgrafnode/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ~/promgrafnode/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - monitoring
    

  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    restart: on-failure
    volumes:
      - ~/promgrafnode/alertmanager/alert-config.yml:/etc/alertmanager/config.yml
      - alertmanager-data:/data
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
      
    ports:
      - 9093:9093
    networks:
      - monitoring

  discord-alerts:
    image: benjojo/alertmanager-discord
    container_name: discord-alerts
    restart: on-failure
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK_URL}
    networks:
      - monitoring  

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    volumes:
      - ~/promgrafnode/blackbox-exporter/blackbox-exporter-config.yml:/etc/blackbox-exporter/config.yml
    command:
      - '--config.file=/etc/blackbox-exporter/config.yml'
    ports:
      - 9115:9115
    networks:
      - monitoring